version: '3.3'
services:
  db:
    image: mongo
    container_name: mongodb-container
    ports:
      - '$MONGO_PORT:27017'
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
      MONGO_USERNAME: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
    volumes:
      - ./mongo_data:/data/db
      - ./backup:/backup
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

