version: '3.4'
services:
  blog-db:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - '$MONGO_PORT:27017'
    command: [--auth]
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
      MONGO_USERNAME: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
    volumes:
      - ./mongo_data:/data/db
      - /wwwroot/static/mongo-backup:/backup
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

