name: Deploy api blog

on:
  # 手动触发
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    # 使用ubuntu系统镜像运行自动化脚本
    runs-on: ubuntu-latest

    steps:

      # 切换分支
      - name: Checkout
        uses: actions/checkout@v2

      #      # 下载 git submodule
      #      - uses: srt32/git-actions@v0.0.3
      #        with:
      #          args: git submodule update --init --recursive

      # 使用 node:14
      - name: use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 缓存 node modules
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # npm install
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      # Create .production.env
      - name: Create .production.env
        env:
          NODE_ENV: production
          PORT: ${{ secrets.APP_PORT }}
          HOST: ${{ secrets.APP_HOST }}
          MONGO_PORT: ${{ secrets.MONGO_PORT }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          ACCESSKEY: ${{ secrets.ACCESSKEY }}
          SECRETKEY: ${{ secrets.SECRETKEY }}
        run: |
          touch .production.env
          echo NODE_ENV="$NODE_ENV" >> .production.env
          echo PORT="$PORT" >> .production.env
          echo HOST="$HOST" >> .production.env
          echo MONGO_PORT="$MONGO_PORT" >> .production.env
          echo MONGO_USER="$MONGO_USER" >> .production.env
          echo MONGO_PASSWORD="$MONGO_PASSWORD" >> .production.env
          echo MONGO_HOST="$MONGO_HOST" >> .production.env
          echo MONGO_DB="$MONGO_DB" >> .production.env
          echo ACCESSKEY="$ACCESSKEY" >> .production.env
          echo SECRETKEY="$SECRETKEY" >> .production.env
        shell: bash

      # build
      - name: Build
        run: npm run build

      # tar
      - name: Tar dist
        run: tar zcf build.tar.gz dist package.json package-lock.json .production.env

      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN_PEM }}
          ARGS: "-avz --delete"
          SOURCE: "build.tar.gz"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '/wwwroot/api-blogs'

      # 远程Command
      - name: Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.ACCESS_TOKEN }}
          script: |
            cd /wwwroot/api-blogs
            tar zxf build.tar.gz
            rm build.tar.gz
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm i
            pm2 delete api-blogs
            npm run pm2
            echo "Complete!!!"
