name: Deploy api blog

on:
  # 手动触发
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    # 使用ubuntu系统镜像运行自动化脚本
    runs-on: ubuntu-latest

    steps:

      # 切换分支
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      # 使用 node:lts/jod
      - name: use Node.js lts/jod
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/jod'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Create .env
      - name: Create .env
        run: |
          touch .env
          echo NODE_ENV="production" >> .env
          echo PORT="${{ secrets.APP_PORT }}" >> .env
          echo HOST="${{ secrets.APP_HOST }}" >> .env
          echo MONGO_URL="${{ secrets.MONGO_URL }}" >> .env
          echo MONGO_USER="${{ secrets.MONGO_USER }}" >> .env
          echo MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" >> .env
          echo MONGO_DB="${{ secrets.MONGO_DB }}" >> .env
          echo BUCKET="${{ secrets.BUCKET }}" >> .env
          echo ACCESS_KEY_ID="${{ secrets.ACCESS_KEY_ID }}" >> .env
          echo SECRET_ACCESS_KEY="${{ secrets.SECRET_ACCESS_KEY }}" >> .env
          echo ENDPOINT="${{ secrets.ENDPOINT }}" >> .env
          echo REGION="${{ secrets.REGION }}" >> .env
        shell: bash

      # build
      - name: Build
        run: pnpm run build

      # tar
      - name: Tar dist
        run: tar zcf build.tar.gz dist package.json package-lock.json pnpm-lock.yaml .env

      # Deploy to server
      - name: Deploy to server
        id: deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          #host: "foo.com,bar.com"
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.ACCESS_TOKEN }}
          source: "build.tar.gz"
          target: /wwwroot/api-blogs

      # 远程Command
      - name: Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.ACCESS_TOKEN }}
          script: |
            cd /wwwroot/api-blogs
            tar zxf build.tar.gz
            rm build.tar.gz
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pnpm i
            pm2 stop api-blogs
            pm2 delete api-blogs
            npm run pm2
            pm2 save
            echo "Complete!!!"
